[package]
name         = "ahead-app"
license      = { workspace = true }
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ahead-viewmodel = { path = "../ahead-viewmodel" }
ahead-rpc       = { workspace = true }
alacritty_terminal = { workspace = true }
portable-pty = "0.8"
chrono          = { workspace = true }
gpui-kit        = { workspace = true }
gpui-kit-assets = "0.6"
uuid            = { version = "1.7", features = ["v4"] }
